### ISSUE TITLE
0.0.9a2 - Page not found

### ISSUE THREAD

**Issue by generallynonsensical** [OpenVoiceOS/ovos-config#41]
Cannot install the latest version 0.0.9a2. Returns with the following error:

`ERROR: Could not find a version that satisfies the requirement ovos-config==0.0.9a2 (from versions: 0.0.0, 0.0.1a2, 0.0.1, 0.0.2a1, 0.0.2a2, 0.0.2a3, 0.0.2a4, 0.0.2, 0.0.3a1, 0.0.3, 0.0.4a1, 0.0.4a2, 0.0.4a3, 0.0.4a4, 0.0.4a5, 0.0.4, 0.0.5a1, 0.0.5a2, 0.0.5a3, 0.0.5a4, 0.0.5a5, 0.0.5a6, 0.0.5, 0.0.6a1, 0.0.6a2, 0.0.6, 0.0.7a1, 0.0.7a2, 0.0.7, 0.0.8a1, 0.0.8a2, 0.0.8a3, 0.0.8a4, 0.0.8a5, 0.0.8, 0.0.9a1)
ERROR: No matching distribution found for ovos-config==0.0.9a2`

0.0.9a1 installs fine

**Comment by JarbasAl** [comment]
where is this error coming from? what is trying to install 0.0.9a2?

**Comment by generallynonsensical** [comment]
I am trying to install 0.0.9a2 via pip
pip install ovos-config==0.0.9a2

**Comment by NeonDaniel** [comment]
Looks like that failed https://github.com/OpenVoiceOS/ovos-config/actions/runs/4909901019/jobs/8766585019
Working on a fix now
