### ISSUE TITLE
ovos-config command line not giving expected response

### ISSUE THREAD

**Issue by Bulwagga** [OpenVoiceOS/ovos-config#59]
I am having several issues like this one that are forcing me to use ed and sed to edit my mycroft.conf.

ovos@raspOvos:~ $ ovos-config **g**et -k /listener/VAD/module
ovos-vad-plugin-silero
ovos@raspOvos:~ $ ovos-config **s**et -k /listener/VAD/module
Error: No key that fits the query
ovos@raspOvos:~ $ ovos-config **s**et -k VAD
│ 0 │ listener/VAD/silence_method                                     │ vad_and_ratio │
│ 1 │ listener/VAD/ovos-vad-plugin-silero/threshold           │ 0.2                   │
│ 2 │ listener/VAD/ovos-vad-plugin-webrtcvad/vad_mode │ 3                      │

but no "module" option.

I can "get" the contents of this field, but cannot "set" the contents of this field. Is this a syntax problem? This same syntax works for other settings.

**Comment by builderjer** [comment]
I can validate this.  I get the same error

**Comment by goldyfruit** [comment]
@JarbasAl having the same issue.

```
$ ovos-config set -k /stt/module -v ovos-stt-plugin-chromium
Error: No key that fits the query
```
