### ISSUE TITLE
Services don't start with malformed configuration

### ISSUE THREAD

**Issue by builderjer** [OpenVoiceOS/ovos-config#97]
I have come across the issue when `/etc/mycroft/mycroft.conf` is malformed, `ovos-messagebus` will not start.

**expected**

Since there is a default config file provided with core, I would expect a warning that this could not be loaded, and skipped instead of creating an error

The file at `~/.config/mycroft/mycroft.conf` is already handled this way.

**Comment by JarbasAl** [comment]
we account for user mistakes, but that file is meant for distros and it being invalid really should be breaking IMHO

you dont want to silence that error or hide it, want to fail loudly so the image maintainers ensure they ship a valid config
